export const mobileCopy = {
  install: "Add to Home Screen",
  iosInstall: "Open this page in Safari, tap Share, then Add to Home Screen.",
  androidInstall: "Open the browser menu and choose Install app or Add to Home screen.",
  unavailable: "The analysis server is unavailable. Please try again later.",
  experimentalSensor: "Experimental sensor",
  notConnected: "Not connected",
  paired: "Paired",
  receivingData: "Receiving data",
  connectionLost: "Connection lost",
  sensorUnavailable: "Sensor data unavailable",
  rawSignal: "Raw experimental sensor signal",
  sensorNotValidated: "These readings are raw, experimental signals. They are not yet calibrated or validated as pressure, force, weight distribution, or hand-load symmetry.",
  pairDevice: "Pair device",
  revokePairing: "Revoke pairing",
  createToken: "Create pairing token",
  tokenExpires: "Token expires",
  receiving: "Receiving",
  sequences: "sequences",
  linkToSession: "Link to a recording",
  unlinkSession: "Unlink from recording",
  noSessions: "No recording sessions available.",
  sessionLinked: "Linked to recording",
  sessionUnlinked: "Not linked to a recording",
  connectionInstructions: "Connection instructions",
  esp32Setup: "ESP32 setup steps",
  simulatorInstructions: "Simulator instructions",
  lanOnly: "LAN HTTP is a prototype-only transport. Keep this endpoint on your local network when possible.",
  attention: "Required for device pairing",
  copyToken: "Copy token",
  tokenCopied: "Token copied",
  pairingCode: "Pairing code",
  deviceId: "Device ID",
  audioCue: "Audio cue during review",
  audioCueOff: "Audio cue off",
  audioCueOn: "Audio cue on",
  playAudioCue: "Play audio cue",
  audioUnavailable: "Speech synthesis is unavailable on this device.",
  keepHipsInLine: "Keep your hips in line.",
  hipsDropped: "Hips dropped below the body line",
  keepShouldersHipsAnklesAligned: "Keep shoulders, hips and ankles aligned",
  bodyAlignment: "Body alignment",
  rangeOfMotion: "Range of motion",
  notAssessed: "Not assessed",
  looksConsistent: "Looks consistent",
  reviewBodyAlignment: "Review: body alignment",
  reviewRangeOfMotion: "Review: range of motion",
  whyThisMatters: "Why this matters",
  howMeasured: "How this was measured",
  issue: "Issue",
  evidence: "Evidence",
  action: "Action",
  watchExactMoment: "Watch exact moment",
  referenceLine: "Reference alignment",
  correction: "Correction",
  alignmentExplanation: "Keeping the shoulders, hips and ankles aligned helps maintain a stable push-up body configuration and reduces compensatory movement.",
  alignmentSource: "https://doi.org/10.1519/SSC.0b013e31826d877b",
  romExplanation: "Movement range changes the mechanical demands and training stimulus of the push-up. The camera estimates elbow angle near the bottom position; it does not confirm chest-to-floor contact.",
  romSource: "https://doi.org/10.1519/jsc.0000000000004415",
  thresholdsNotValidated: "These sources support the biomechanical criteria. The prototype’s numerical thresholds have not yet been independently validated.",
  insufficientLandmarks: "Camera angle or landmark quality was insufficient to assess this repetition.",
  bodyAlignmentMovedOutside: "Body alignment moved outside the assessed range.",
  persistentHipIssue: "The hip position remained outside the current alignment range for {duration}.",
  persistentRomIssue: "The lowering range stayed outside the assessed range for {duration}.",
} as const;
