"use client";
import { useEffect, useState } from "react";
import { apiFetch } from "@/lib/api";
import Link from "next/link";

type Device = { pairing_id: string; device_id: string; state: string; last_seen_at: string | null; last_sequence: number | null; channels: Array<{ channel_id: string; raw_value: number }> };
export function ExperimentalSensor() {
  const [devices, setDevices] = useState<Device[]>([]);
  const [deviceId, setDeviceId] = useState("esp32-demo-01");
  const [token, setToken] = useState("");
  const [pairing, setPairing] = useState(false);
  const [expiresInMinutes, setExpiresInMinutes] = useState(15);
  const [sessionId, setSessionId] = useState("");
  const [error, setError] = useState("");
  const refresh = async () => { try { const response = await apiFetch("/api/sensors"); if (!response.ok) throw new Error("Sensor status unavailable."); setDevices(((await response.json()) as { devices: Device[] }).devices); setError(""); } catch (cause) { setError(cause instanceof Error ? cause.message : "Sensor status unavailable."); } };
  useEffect(() => { const first = window.setTimeout(() => void refresh(), 0); const interval = window.setInterval(() => void refresh(), 5000); return () => { window.clearTimeout(first); window.clearInterval(interval); }; }, []);
  const pair = async () => { if (pairing) return; setPairing(true); setToken(""); try { const response = await apiFetch("/api/sensors/pairings", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ device_id: deviceId, workout_session_id: sessionId.trim() || null }) }); if (!response.ok) { setError(((await response.json()) as {detail?: string}).detail ?? "Pairing failed."); return; } const created = (await response.json()) as {token: string; expires_in_seconds: number; sequence: number}; setToken(created.token); setExpiresInMinutes(Math.round(created.expires_in_seconds / 60)); void refresh(); } catch { setError("Pairing failed."); } finally { setPairing(false); } };
  const revoke = async (id: string) => { const response = await apiFetch(`/api/sensors/pairings/${id}`, { method: "DELETE" }); if (!response.ok) setError("Could not revoke this pairing."); else { setToken(""); void refresh(); } };
  return <main className="sensor-page"><Link href="/?screen=app">← Back to training</Link><header><p className="eyebrow">Optional connection</p><h1>Experimental sensor</h1><p>Live experimental sensor connection. Raw readings are separate from camera conclusions.</p></header><section className="sensor-panel"><h2>Pair an ESP32 or simulator</h2><label>Device ID <input value={deviceId} onChange={event => setDeviceId(event.target.value)} maxLength={64} /></label><button disabled={pairing} onClick={() => void pair()}>Create pairing token</button><label>Workout session ID (optional) <input value={sessionId} onChange={event => setSessionId(event.target.value)} placeholder="Paste current session ID" /></label><p>Enter your current workout session ID before pairing to link incoming raw readings. The backend checks session ownership.</p>{token && <div className="sensor-token"><strong>Copy this token now. It is shown only once.</strong><code>{token}</code><p>Expires in {expiresInMinutes} minutes. Put it in the device configuration, never in the browser URL.</p></div>}</section>{error && <p role="alert">{error}</p>}<section className="sensor-panel"><h2>Connection status</h2>{devices.length === 0 ? <p>Not connected</p> : devices.map(device => <article key={device.pairing_id}><h3>{device.device_id}</h3><p>{device.state}</p><p>Last sequence: {device.last_sequence ?? "Unavailable"}</p>{device.state === "Receiving data" ? <div><strong>Raw experimental sensor signal</strong><ul>{device.channels.map(channel => <li key={channel.channel_id}>{channel.channel_id}: {channel.raw_value}</li>)}</ul></div> : <p>Sensor data unavailable</p>}<button onClick={() => void revoke(device.pairing_id)}>Revoke pairing</button></article>)}</section><p className="sensor-boundary">Experimental sensor readings are not part of the primary technique result until calibration and validation are complete. The current camera pipeline does not measure pressure, force, weight distribution, contact position or left/right hand loading. The product is not a medical device. The current workflow is post-session review, not live coaching.</p><details><summary>Connection instructions</summary><p>Connect the ESP32 and laptop to the same Wi-Fi. Send telemetry to the laptop LAN address on port 8001. LAN HTTP is a prototype-only transport; restrict it to your local network. Your phone may use an HTTPS tunnel to view this PWA.</p></details></main>;
}
